"use client";
import {useMemo,useState} from "react";
import {DEFAULT_POLICY,evaluatePayment,SafetyPolicy} from "../lib/safety";

type Event={time:string;action:string;amount?:number;status:string;tx?:string};
export default function Home(){
 const [policy,setPolicy]=useState<SafetyPolicy>(DEFAULT_POLICY); const [amount,setAmount]=useState("0.80"); const [spent,setSpent]=useState(0); const [events,setEvents]=useState<Event[]>([]); const [running,setRunning]=useState(true); const [approved,setApproved]=useState(false);
 const result=useMemo(()=>evaluatePayment(Number(amount),spent,policy),[amount,spent,policy]);
 function run(){if(!running)return; if(!result.allowed){setEvents(e=>[{time:new Date().toLocaleTimeString(),action:"Payment blocked",status:result.reason},...e]);return;} if(policy.approvalRequired&&!approved){setEvents(e=>[{time:new Date().toLocaleTimeString(),action:"Approval required",amount:Number(amount),status:"WAITING_FOR_USER"},...e]);return;} setSpent(v=>v+Number(amount));setApproved(false);setEvents(e=>[{time:new Date().toLocaleTimeString(),action:"Agent payment",amount:Number(amount),status:"SIMULATED_OK",tx:"demo_xlayer_tx_"+Math.random().toString(16).slice(2,10)},...e]);}
 return <main><nav><div className="brand">XAVERUS<span>SAFE AGENT PASSPORT</span></div><div className="pill">OKX / X LAYER · DEMO SAFE MODE</div></nav><section className="hero"><div><div className="eyebrow">USER-CONTROLLED AGENT SAFETY</div><h1>Let agents act.<br/><em>You keep the keys.</em></h1><p>Xaverus gives every user a personal policy layer for autonomous payments: limits, approval gates, kill switch and proof-of-action history.</p><button className="primary" onClick={()=>setRunning(true)}>Activate Passport</button></div><div className="passport"><div className="passportTop"><span>SAFETY PASSPORT</span><b>{running?"ACTIVE":"STOPPED"}</b></div><div className="ring">{running?"✓":"!"}</div><div className="passportId">LOCAL DEMO ID<br/><strong>XAV-{typeof window!=="undefined"?window.location.hostname.toUpperCase():"USER"}-01</strong></div><div className="checks"><span>✓ Spend policy</span><span>✓ Approval gate</span><span>✓ Kill switch</span><span>✓ Audit trail</span></div></div></section>
 <section className="grid"><div className="card"><div className="cardHead"><h2>Safety policy</h2><span className="status">ENFORCED</span></div><label>Max per transaction <input type="number" value={policy.perTx} onChange={e=>setPolicy({...policy,perTx:Number(e.target.value)})}/><small>USDC</small></label><label>Daily spend cap <input type="number" value={policy.daily} onChange={e=>setPolicy({...policy,daily:Number(e.target.value)})}/><small>USDC</small></label><label className="toggle"><input type="checkbox" checked={policy.approvalRequired} onChange={e=>setPolicy({...policy,approvalRequired:e.target.checked})}/><span>Require user approval</span></label><label className="toggle"><input type="checkbox" checked={policy.autoStop} onChange={e=>setPolicy({...policy,autoStop:e.target.checked})}/><span>Auto-stop on policy violation</span></label><button className="danger" onClick={()=>setRunning(false)}>⏹ Kill switch</button></div>
 <div className="card"><div className="cardHead"><h2>Agent payment</h2><span className={result.allowed?"status":"status bad"}>{result.allowed?"POLICY OK":"BLOCKED"}</span></div><div className="task">Agent task <b>Pay data-service for verified result</b><span>Agent → Service · X Layer · USDC</span></div><label>Amount <input value={amount} onChange={e=>setAmount(e.target.value)}/><small>USDC</small></label><div className="preview"><span>Intent preview</span><strong>{result.reason}</strong><div><span>Spent today</span><b>{spent.toFixed(2)} / {policy.daily.toFixed(2)} USDC</b></div></div>{policy.approvalRequired&&!approved&&result.allowed&&<button className="approve" onClick={()=>setApproved(true)}>Approve this intent</button>}<button className="primary wide" onClick={run}>{approved||!policy.approvalRequired?"Execute agent payment":"Simulate & request approval"}</button></div>
 <div className="card audit"><div className="cardHead"><h2>Proof-of-action</h2><span>{events.length} EVENTS</span></div>{events.length===0?<div className="empty">No actions yet. Every decision will appear here.</div>:events.map((e,i)=><div className="event" key={i}><div><b>{e.action}</b><span>{e.time}{e.tx?" · "+e.tx:""}</span></div><strong className={e.status.includes("OK")?"good":e.status.includes("WAIT")?"wait":"bad"}>{e.status}</strong></div>)}</div></section>
 <footer><span>XAVERUS · SAFE AGENT PASSPORT</span><span>Built for OKX Dev Day · Demo-safe architecture</span></footer></main>}